### ISSUE TITLE
连接地址有错啊

### ISSUE THREAD

**Issue by jalena** [tencentyun/coscmd#107]
错误信息
```[root@VM_90_158_centos ~]# coscmd list -a
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 765, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/site-packages/coscmd/cos_cmd.py", line 564, in command_thread
    res = args.func(args)
  File "/usr/lib/python2.7/site-packages/coscmd/cos_cmd.py", line 265, in list
    if Interface.list_objects(cos_path=args.cos_path, _recursive=args.recursive, _all=args.all, _num=args.num, _human=args.human):
  File "/usr/lib/python2.7/site-packages/coscmd/cos_client.py", line 892, in list_objects
    rt = self._session.get(url=url, auth=CosS3Auth(self._conf._secret_id, self._conf._secret_key))
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='-mybucket.cos.ap-chengdu.myqcloud.com', port=443): Max retries exceeded with url: /?prefix=&marker=&delimiter=/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x1fa7650>: Failed to establish a new connection: [Errno -2] Name or service not known',))
```

配置文件
```[common]
secret_id = ak
secret_key = sk
bucket = mybucket
region = ap-chengdu
max_thread = 5
part_size = 1
```

问题版本`coscmd 1.8.2.10`
python`Python 2.7.5`
PIP`pip 9.0.1 from /usr/lib/python2.7/site-packages (python 2.7)`

**Comment by Liuchang0812** [comment]
`bucket`  应该带上 appid

**Comment by lewzylu** [comment]
for example 
bucket = mybucket-125xxxxxxxx

**Comment by jalena** [comment]
例子没看对。。。。
