### ISSUE TITLE
Can not use coscmd after install.

### ISSUE THREAD

**Issue by ChaiZhi** [tencentyun/coscmd#145]
Traceback (most recent call last):
  File "/Users/happyelements/miniconda3/envs/heai/bin/coscmd", line 7, in <module>
    from coscmd.cos_cmd import _main
  File "/Users/happyelements/miniconda3/envs/heai/lib/python3.6/site-packages/coscmd/cos_cmd.py", line 2, in <module>
    from cos_client import CosConfig, CosS3Client
ModuleNotFoundError: No module named 'cos_client'

python version is 3.6.5
**from cos_client import CosConfig, CosS3Client**
should be like:
**from coscmd.cos_client import CosConfig, CosS3Client**

**Comment by reinhouthooft** [comment]
Test build still failing as well, any update on the testing part?

**Comment by lewzylu** [comment]
test is ok now
