### ISSUE TITLE
coscmd命令报错ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+

### ISSUE THREAD

**Issue by imaegoo** [tencentyun/coscmd#300]
```
[executionStep begins at 2023-05-12 10:08:13]
[INFO] PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/alibaba/install/python-3.8.5/bin/python3
/root/entry.sh: line 53: export: `,': not a valid identifier
/root/entry.sh: line 53: export: `,': not a valid identifier
[92m[10:08:14] [SUCCESS]
[1m[10:08:14] [INFO] /root/workspace/blog
[1m[10:08:14] [INFO]
[10:08:14] [INFO]PIPELINE_ID=2026193
[10:08:14] [INFO]PIPELINE_NAME=blog
[10:08:14] [INFO]BUILD_NUMBER=88
[10:08:14] [INFO]EMPLOYEE_ID=61245fd2cd146a5e9cabbe6f
[10:08:14] [INFO]WORK_SPACE=/root/workspace
[10:08:14] [INFO]PROJECT_DIR=/root/workspace/blog
[10:08:14] [INFO]BUILD_JOB_ID=126009117
[10:08:14] [INFO]执行用户命令
[1;36m[10:08:14] [User Command] + pip install coscmd
[10:08:15] Collecting coscmd
[10:08:15]   Using cached coscmd-1.8.6.31-py3-none-any.whl
[10:08:16] Collecting datetime>=4.2
[10:08:16]   Using cached DateTime-5.1-py3-none-any.whl (52 kB)
[10:08:16] Collecting pyyaml>=3
[10:08:16]   Using cached PyYAML-6.0-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (701 kB)
[10:08:16] Collecting prettytable>=0.7
[10:08:16]   Using cached prettytable-3.7.0-py3-none-any.whl (27 kB)
[10:08:16] Collecting tqdm>=4.15.0
[10:08:16]   Using cached tqdm-4.65.0-py3-none-any.whl (77 kB)
[10:08:16] Collecting requests>=2.8
[10:08:16]   Downloading requests-2.30.0-py3-none-any.whl (62 kB)
[10:08:16]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.5/62.5 kB 5.9 MB/s eta 0:00:00
[10:08:16] Collecting argparse>=1.4.0
[10:08:16]   Using cached argparse-1.4.0-py2.py3-none-any.whl (23 kB)
[10:08:16] Collecting pytz>=2017.2
[10:08:16]   Using cached pytz-2023.3-py2.py3-none-any.whl (502 kB)
[10:08:16] Requirement already satisfied: six>=1.11.0 in /usr/local/lib/python3.8/site-packages (from coscmd) (1.15.0)
[10:08:17] Collecting cos-python-sdk-v5>=1.9.8
[10:08:17]   Downloading cos-python-sdk-v5-1.9.24.tar.gz (96 kB)
[10:08:17]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.3/96.3 kB 27.1 MB/s eta 0:00:00
[10:08:17]   Preparing metadata (setup.py): started
[10:08:17]   Preparing metadata (setup.py): finished with status 'done'
[10:08:17] Collecting xmltodict
[10:08:17]   Using cached xmltodict-0.13.0-py2.py3-none-any.whl (10.0 kB)
[10:08:17] Collecting crcmod
[10:08:17]   Using cached crcmod-1.7-cp38-cp38-linux_x86_64.whl
[10:08:17] Collecting pycryptodome
[10:08:17]   Using cached pycryptodome-3.17-cp35-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.1 MB)
[10:08:18] Collecting zope.interface
[10:08:18]   Using cached zope.interface-6.0-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (249 kB)
[10:08:18] Collecting wcwidth
[10:08:18]   Using cached wcwidth-0.2.6-py2.py3-none-any.whl (29 kB)
[10:08:18] Collecting certifi>=2017.4.17
[10:08:18]   Downloading certifi-2023.5.7-py3-none-any.whl (156 kB)
[10:08:18]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 157.0/157.0 kB 42.9 MB/s eta 0:00:00
[10:08:18] Collecting charset-normalizer<4,>=2
[10:08:18]   Using cached charset_normalizer-3.1.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (195 kB)
[10:08:18] Collecting idna<4,>=2.5
[10:08:18]   Using cached idna-3.4-py3-none-any.whl (61 kB)
[10:08:18] Collecting urllib3<3,>=1.21.1
[10:08:18]   Downloading urllib3-2.0.2-py3-none-any.whl (123 kB)
[10:08:18]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 123.2/123.2 kB 34.9 MB/s eta 0:00:00
[10:08:18] Requirement already satisfied: setuptools in /usr/local/lib/python3.8/site-packages (from zope.interface->datetime>=4.2->coscmd) (47.1.0)
[10:08:18] Building wheels for collected packages: cos-python-sdk-v5
[10:08:18]   Building wheel for cos-python-sdk-v5 (setup.py): started
[10:08:19]   Building wheel for cos-python-sdk-v5 (setup.py): finished with status 'done'
[10:08:19]   Created wheel for cos-python-sdk-v5: filename=cos_python_sdk_v5-1.9.24-py3-none-any.whl size=89922 sha256=e93675113caf37b42274af3a4efd8b28eb1c5f76c7ec2001fb2a67fb98196d78
[10:08:19]   Stored in directory: /root/.cache/pip/wheels/d5/19/5a/ae9a72439af360b20f29096db8b1a160369ffb33e666519c0f
[10:08:19] Successfully built cos-python-sdk-v5
[10:08:19] Installing collected packages: wcwidth, pytz, crcmod, argparse, zope.interface, xmltodict, urllib3, tqdm, pyyaml, pycryptodome, prettytable, idna, charset-normalizer, certifi, requests, datetime, cos-python-sdk-v5, coscmd
[10:08:20] Successfully installed argparse-1.4.0 certifi-2023.5.7 charset-normalizer-3.1.0 cos-python-sdk-v5-1.9.24 coscmd-1.8.6.31 crcmod-1.7 datetime-5.1 idna-3.4 prettytable-3.7.0 pycryptodome-3.17 pytz-2023.3 pyyaml-6.0 requests-2.30.0 tqdm-4.65.0 urllib3-2.0.2 wcwidth-0.2.6 xmltodict-0.13.0 zope.interface-6.0
[10:08:20] WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[10:08:21] 
[10:08:21] [notice] A new release of pip is available: 23.0.1 -> 23.1.2
[10:08:21] [notice] To update, run: pip install --upgrade pip
[1;36m[10:08:21] [User Command] + coscmd config -a **** -s **** -b **** -r ap-shanghai
[10:08:21] Traceback (most recent call last):
[10:08:21]   File "/usr/local/bin/coscmd", line 5, in <module>
[10:08:21]     from coscmd.cos_cmd import _main
[10:08:21]   File "/usr/local/lib/python3.8/site-packages/coscmd/cos_cmd.py", line 10, in <module>
[10:08:21]     import requests
[10:08:21]   File "/usr/local/lib/python3.8/site-packages/requests/__init__.py", line 43, in <module>
[10:08:21]     import urllib3
[10:08:21]   File "/usr/local/lib/python3.8/site-packages/urllib3/__init__.py", line 38, in <module>
[10:08:21]     raise ImportError(
[10:08:21] ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with OpenSSL 1.0.2e 3 Dec 2015. See: https://github.com/urllib3/urllib3/issues/2168
[91m[10:08:21] [ERROR] BUILD ERROR
[91m[10:08:21] [ERROR] 126009117
[91m[10:08:21] [ERROR] 1
```

**Comment by imaegoo** [comment]
补充：5月1日还可以，配置没改过，今天发现不行了

![image](https://github.com/tencentyun/coscmd/assets/20182252/25ac40db-0901-40de-9485-6adc032cfd7b)

**Comment by imaegoo** [comment]
流水线加了一行命令解决

```
pip install urllib3==1.26.15
```
