### ISSUE TITLE
不支持python3.12

### ISSUE THREAD

**Issue by lijc210** [tencentyun/coscmd#311]
from six.moves.configparser import SafeConfigParser
ImportError: cannot import name 'SafeConfigParser' from 'configparser'

**Comment by SidHard** [comment]
same error

**Comment by lewzylu** [comment]
The latest code on the master already supports Python 3.12; 
However, due to compatibility considerations with Python 2, no pypi has been released yet

**Comment by OnlyAR** [comment]
Install with pip and traceback below:

```text
Traceback (most recent call last):
  File "/home/Jun/env/miniconda3/bin/coscmd", line 5, in <module>
    from coscmd.cos_cmd import _main
  File "/home/Jun/env/miniconda3/lib/python3.12/site-packages/coscmd/cos_cmd.py", line 2, in <module>
    from six.moves.configparser import SafeConfigParser
ImportError: cannot import name 'SafeConfigParser' from 'configparser' (/home/Jun/env/miniconda3/lib/python3.12/configparser.py). Did you mean: 'RawConfigParser'?
(base) Jun@deepin:~$ coscmd -h  
Traceback (most recent call last):
  File "/home/Jun/env/miniconda3/bin/coscmd", line 5, in <module>
    from coscmd.cos_cmd import _main
  File "/home/Jun/env/miniconda3/lib/python3.12/site-packages/coscmd/cos_cmd.py", line 2, in <module>
    from six.moves.configparser import SafeConfigParser
ImportError: cannot import name 'SafeConfigParser' from 'configparser' (/home/Jun/env/miniconda3/lib/python3.12/configparser.py). Did you mean: 'RawConfigParser'?
```

I opened the file `coscmd/cos_cmd.py` and simply change `SafeConfigParser` to `RawConfigParser`, and it dose work.

Although it's not elegant enough.

**Comment by yuangezhizao** [comment]
通过修改如下命令可以安装`master`分支的`pip`包而无需降低`Python 3.12`的版本，供参考
- 修改前：`pip install coscmd`
- 修改后：`pip install https://github.com/tencentyun/coscmd/archive/refs/heads/master.zip`
