### ISSUE TITLE
我也是从官网来的，windows下怎么用？

### ISSUE THREAD

**Issue by 1291061979** [tencentyun/coscmd#62]
要安装这个先安装pip
要安装pip又会报新的错
新的错网上有人让安装一个 distribute_setup
经过从大量多年以前的过期文章中筛选
终于找到方法安装好pip，当然中间会有更多报错
输入 pip install coscmd 
又有新的报错
Traceback (most recent call last):
  File "C:\Python27\Scripts\pip-script.py", line 11, in <module>
    load_entry_point('pip==9.0.1', 'console_scripts', 'pip')()
  File "C:\Python27\lib\site-packages\distribute-0.6.27-py2.7.egg\pkg_resources.py", line 337, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Python27\lib\site-packages\distribute-0.6.27-py2.7.egg\pkg_resources.py", line 2307, in load_entry_point
    return ep.load()
  File "C:\Python27\lib\site-packages\distribute-0.6.27-py2.7.egg\pkg_resources.py", line 2017, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "C:\Python27\lib\site-packages\pip-9.0.1-py2.7.egg\pip\__init__.py", line 28, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "C:\Python27\lib\site-packages\pip-9.0.1-py2.7.egg\pip\vcs\mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "C:\Python27\lib\site-packages\pip-9.0.1-py2.7.egg\pip\download.py", line 37, in <module>
    from pip.utils.ui import DownloadProgressBar, DownloadProgressSpinner
  File "C:\Python27\lib\site-packages\pip-9.0.1-py2.7.egg\pip\utils\ui.py", line 57, in <module>
    _BaseBar = _select_progress_class(IncrementalBar, Bar)
  File "C:\Python27\lib\site-packages\pip-9.0.1-py2.7.egg\pip\utils\ui.py", line 50, in _select_progress_class
    six.text_type().join(characters).encode(encoding)
LookupError: unknown encoding: cp65001

总之想用这个，至少涉及到pip easy_install pkg_resources等一大堆东西（目前记得这几个词），如果想解决新的报错，又要安装新的依赖，而且无法预期到底还需要多少... ...

**Comment by Liuchang0812** [comment]
你的终端编码问题，先执行 `chcp 936`
